spring:
  application:
    name: umbrella-return
  profiles:
    active: local
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

aligo:
  api-key: ${ALIGO_API_KEY:test-key}
  user-id: ${ALIGO_USER_ID:test-user}
  sender: ${ALIGO_SENDER:01000000000}
